version: "3.8"

services:
  service1:
    build: ./service_1
    ports:
      - "8001:8001"
    container_name: service1

  service2:
    build: ./service_2
    ports:
      - "8002:8002"
    container_name: service2

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    container_name: nginx-proxy
